// A set of the 18 minerals in our lab, plus an unassigned option - Amber Patterson
public enum mineralType
{
    QUARTZ, GYPSUM, PYRITE, HORNBLENDE, CALCITE, OLIVINE, KAOLINITE, GARNET, GALENA, HEMATITE, PLAGIOCLASE_FELDSPAR, BIOTITE, ROSE_QUARTZ, MUSCOVITE, POTASSIUM_FELDSPAR, HALITE, AUGITE, UNASSIGNED
}